---
title: "Visualizing data from Excel"
author: "Shervin Kaandorp"
date: "14-4-2021"
output: html_document
---
```{R Setup, include=FALSE}
library(tidyverse)
library(readxl)
library(here)
```

# Visualizing data from Excel

The data I am using is CE.LIQ.FLOW.062_Tidydata.xlsx which is an experiment where C.elegans nematodes were incubated in different compounds with different concentrations. This dataset was provided by J. Louter which is a researcher for the Lectoraat of the Institute for Life Sciences. Some variables are key to the visualization: the RawData, which is the number of offspring of the C. elegans, the compName, which is the compound in which the C. elegans was incubated and the compConcentration, which is the concentration in which the C. elegans was incubated. Here, i'll visualize the data to a graph with _ggplot2_. 

There are some values missing in the "RawData" column in row 192-196. RawData, compName, compConcentration and the expType column all have a General format in Excel. While it is expected that they have a text format. Cell P260 has a comma instead of a dot.

The _here_ and _readxl_ packages have been used to import the excel file from the working directory.

```{R Assignment 1.1B, message=FALSE}
CE.LIQ.FLOW.062_Tidydata <- read_excel(here("rawdata/CE.LIQ.FLOW.062_Tidydata.xlsx"))
```

The variables are inspected with the str() command.

```{R Assignment 1.1C}
as_tibble(CE.LIQ.FLOW.062_Tidydata) %>% select("RawData","compName","compConcentration") %>% str()
```

The data of the "RawData" and "compName" columns have been assinged correctly. Nonetheless, the data type for "compConcentration" has been assinged incorrectly. This should have been numeric instead of character.

The data has been visualized using the code here.

```{R Assignment 1.1D, warning=FALSE}
CE.LIQ.FLOW.062_Tidydata$compConcentration <- 
  gsub(",", ".", CE.LIQ.FLOW.062_Tidydata$compConcentration) # Resolving issue comma in cell P260.

CE.LIQ.FLOW.062_Tidydata$compConcentration <- as.numeric(CE.LIQ.FLOW.062_Tidydata$compConcentration, na.rm=TRUE) # Change type of compConcentration to numeric

ggplotCLF.062 <- CE.LIQ.FLOW.062_Tidydata %>% 
  ggplot(aes(x=compConcentration,y=RawData,shape=expType,colour=compName)) +
  geom_point() +
  labs(x= "Compound Concentration (nM)",
       y= "Number of offspring",
       title= "Number of offsprings of C.elegans after incubating in a compound",
       caption= "the dataset CE.LIQ.FLOW.062_Tidydata has been used",
       shape="Experiment Type",
       colour="Compound") # Creating graph

ggplotCLF.062
```

Without using the as.numeric function, the x-axis would not be ordered correctly.

Because the values are very close to each other, a log10 transformation of the x-axis and a jitter was added.

```{R Assignment 1.1F, warning=FALSE} 
ggplotCLF.062 + 
  scale_x_continuous(trans = "log10") + 
  geom_jitter(width=0.15) + 
  labs(caption="the dataset CE.LIQ.FLOW.062_Tidydata has been used and a jitter of 0.15 has been added.")
```

The positive control for this experiment is Ethanol and the negative control for this experiment is S-medium.

To analyze the data, these steps should be performed:

1. The mean offspring of each concentration of each compound should be calculated.
2. The mean offspring of each concentration of each compound should be normalized with the mean offspring of the negative control.
3. Now, a IC50 curve can be made depicting the concentration of the compound on the x-axis and the relative offspring on the y-axis.
4. Additional significance tests are performed to examine a possible significant difference.

The data will be normalized for the negative control (controlNegative) and a graph with the normalized data is made with the _ggplot2_ package (comes with _tidyverse_):

```{R Assignment 1.1J, warning=FALSE, message=FALSE}
CE.LIQ.FLOW.062_means <- CE.LIQ.FLOW.062_Tidydata %>%
  group_by(compName,compConcentration, expType) %>% 
  summarize(mean=mean(RawData, na.rm=TRUE)) # Calculating mean

S_medium_neg <- CE.LIQ.FLOW.062_means %>% 
  filter(compName=="S-medium")
negative_cont <- S_medium_neg[4] # Retrieving negative control mean

CE.LIQ.FLOW.062_means <- CE.LIQ.FLOW.062_means %>% 
  mutate(relative_offspring=mean/negative_cont*100) # Adding relative offspring count

CE.LIQ.FLOW.062_means %>%
  ggplot(aes(x=compConcentration,y=relative_offspring$mean,shape=expType,colour=compName)) +
  geom_point() +
  labs(x= "Compound Concentration (nM)",
       y= "Relative number of offspring (%)",
       title= "Relative C.elegans offspring after incubating in a compound",
       caption= "the dataset CE.LIQ.FLOW.062_Tidydata has been used, 
       and the offspring count have been normalized for the negative control.",
       shape="Experiment Type",
       colour="Compound") +
  scale_x_continuous(trans = "log10") # Creating graph
```

To see whether or not there are significant differences, significance tests should be performed. Also a IC50 Curve can be made to visualize the data.